name: CD - Load to master repo
on:
  push:
    branches: [ main ]

# Define name of script
env:
  scriptname: m-script-name.py

jobs:
  build:
    if: github.repository != 'cchowthi/gilead_script_template'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: main
 
      - name: Checkout destination rep
        uses: actions/checkout@v2
        with:
          repository: cchowthi/scripts
          token: ${{ secrets.global_pat }}
          path: scripts
          
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Commit to destination repo
        run: |
          cd scripts
          cp ../main/${{ env.scriptname }} ./
          git config --global user.name "${{ secrets.global_name }}"
          git config --global user.email  "${{ secrets.global_email }}"
          git fetch
          git checkout main
          git add ${{ env.scriptname }}
          git diff-index --quiet HEAD || git commit -m "Automatic update of scripts"
          git push
